// Package auth only handles authentication: password hashing and signed-cookie sessions.
package auth

import (
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256" // sha256 is used for HMAC-based session token signing
	"encoding/base64"
	"fmt" // fmt is used for string formatting
	"strconv"
	"strings"
	"time" // time is used for time-related operations

	"golang.org/x/crypto/bcrypt" // bcrypt is used for password hashing
)

// HashPassword returns a bcrypt hash of password, stored in config.yaml that is generated by `ai-guard init`.
func HashPassword(password string) (string, error) {
	hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		return "", fmt.Errorf("hashing password: %w", err)
	}
	return string(hash), nil
}

// VerifyPassword reports whether password matches the given bcrypt hash.
func VerifyPassword(hash, password string) bool {
	return bcrypt.CompareHashAndPassword([]byte(hash), []byte(password)) == nil
}

// GenerateSecret returns a random secret for signing session tokens.
func GenerateSecret() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("generating session secret: %w", err)
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}

// SessionTTL is how long a session cookie stays valid after login.
const SessionTTL = 10 * 24 * time.Hour // 10 days for security purposes.

// What is this? This function generates a new session token for the given username.
func NewSessionToken(secret, username string) string {
	expiry := time.Now().Add(SessionTTL).Unix()
	return signToken(secret, username, expiry)
}

func signToken(secret, username string, expiry int64) string {
	payload := username + "." + strconv.FormatInt(expiry, 10)
	sig := signPayload(secret, payload)
	return base64.RawURLEncoding.EncodeToString([]byte(payload)) + "." + sig
}

func signPayload(secret, payload string) string {
	mac := hmac.New(sha256.New, []byte(secret))
	mac.Write([]byte(payload))
	return base64.RawURLEncoding.EncodeToString(mac.Sum(nil))
}

// VerifySessionToken verifies a session token against the given secret and returns the authenticated username if the signature is intact and it hasn't expired.
func VerifySessionToken(secret, token string) (username string, ok bool) {
	payloadB64, sig, found := strings.Cut(token, ".")
	if !found {
		return "", false
	}
	payload, err := base64.RawURLEncoding.DecodeString(payloadB64)
	if err != nil {
		return "", false
	}

	expectedSig := signPayload(secret, string(payload))
	if !hmac.Equal([]byte(sig), []byte(expectedSig)) {
		return "", false
	}

	name, expiryStr, found := strings.Cut(string(payload), ".")
	if !found {
		return "", false
	}
	expiry, err := strconv.ParseInt(expiryStr, 10, 64)
	if err != nil {
		return "", false
	}
	if time.Now().Unix() > expiry {
		return "", false
	}
	return name, true
}
